# Generated by Django 5.1 on 2024-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='file_path_field',
            field=models.FilePathField(path='./project_1/'),
        ),
    ]
